version: '3'

services:
  reverseproxy:
    image: nginx:stable-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./pointclouds:/pointclouds:ro
    ports:
      - 127.0.0.1:8000:80
    restart: always

  viewer:
    build: .
    restart: always
